version: "3"
services:
  lb:
    image: dockercloud/haproxy
    links:
      - truth
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3333:80"
  truth:
    image: pjpritch/truth-service
    build:
      context: .
      args:
        - NODE_ENV=development
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/test
      - AMQP_URL=amqp://user:user@rabbitmq
      - ES_URL=es:9200
      - REDIS_URL=redis://redis:6379/1
      - TENANT_TOKEN=123
      - USE_MQ=true
      - EXCLUDE_PORTS=9229
    volumes:
      - "./:/usr/src/app"
    ports:
      - "3000"
      - "9229:9229"
    command: "./node_modules/.bin/nodemon --nolazy --inspect=0.0.0.0:9229 ./bin/www"
    links:
      - mongo
      - es
      - redis
      - rabbitmq
  truth-worker:
    image: pjpritch/truth-service
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/test
      - AMQP_URL=amqp://user:user@rabbitmq
      - ES_URL=es:9200
      - REDIS_URL=redis://redis:6379/1
      - TENANT_TOKEN=123
      - DEBUG=queue-worker
    volumes:
      - "./:/usr/src/app"
    healthcheck:
      disable: true
    command: "node queue-worker.js"
    links:
      - mongo
      - es
      - redis
      - rabbitmq
    depends_on:
      - truth
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: user
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "3334:8081"
    links:
      - mongo
  mongo:
    image: mongo
    command: --smallfiles
    restart: always
    environment:
      MONGO_INITDB_DATABASE: global
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    ports:
      - "9200:9200"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  redis:
    image: redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
      - RABBITMQ_ERLANG_COOKIE='secret quirrel'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitdata1:/var/lib/rabbitmq
    
volumes:
  mongodb:
    driver: local
  esdata1:
    driver: local
  rabbitdata1:
    driver: local
