// Copyright 2019 Peter Pritchard.  All rights reserved.

module.exports = {
  ES_WAIT_TIME: 1000,
  DEFAULT_MONGO_URL: 'mongodb://127.0.0.1:27017/test',
  DEFAULT_REDIS_URL: 'redis://127.0.0.1:6379/1',
  DEFAULT_ES_URL: 'localhost:9200',
  DEFAULT_CACHE_PERIOD: 60,
  DEFAULT_COUNT: 24,
  ENTITY_COLLECTION_NAME: '_entities',
  ENTITY_API_VERSION: 1,
  GLOBAL_NAMESPACE: 'global',
  TENANT_COLLECTION_NAME: 'tenants',
  TENANT_API_VERSION: 1,
  TEMPLATE_COLLECTION_NAME: '_templates',
  TEMPLATE_API_VERSION: 1,
  CONTEXT_COLLECTION_NAME: '_contexts',
  CONTEXT_API_VERSION: 1,
  INSTANCE_API_VERSION: 1,
  X_TENANT_TOKEN: 'x-tenant-token',
  X_STORE_TOKEN: 'x-store-token',
  DEFAULT_API_ERROR: 400,
  API_RATE_LIMIT_WINDOW_MS: 15 * 60 * 1000, // 15 minutes
  API_RATE_LIMIT_MAX: 100,
};
